-- APP
GRANT USAGE ON SCHEMA ":APP_SCHEMA" TO ":APP_USER";

GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA ":APP_SCHEMA" TO ":APP_USER";
ALTER DEFAULT PRIVILEGES IN SCHEMA ":APP_SCHEMA" GRANT SELECT, INSERT, UPDATE ON TABLES TO ":APP_USER";

GRANT SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA ":APP_SCHEMA" TO ":APP_USER";
ALTER DEFAULT PRIVILEGES IN SCHEMA ":APP_SCHEMA" GRANT SELECT, UPDATE ON SEQUENCES TO ":APP_USER";
