-- Drop schemas
DROP SCHEMA IF EXISTS public CASCADE;
DROP SCHEMA IF EXISTS ":APP_SCHEMA" CASCADE;

-- APP roles
DROP ROLE IF EXISTS ":APP_OWNER";
CREATE ROLE ":APP_OWNER" WITH LOGIN PASSWORD '":APP_OWNER_PASSWORD"';
DROP ROLE IF EXISTS ":APP_USER";
CREATE ROLE ":APP_USER" WITH LOGIN PASSWORD '":APP_USER_PASSWORD"';

-- Grant connects to databases
GRANT CONNECT ON DATABASE ":POSTGRES_DB" TO ":APP_OWNER";
GRANT CONNECT ON DATABASE ":POSTGRES_DB" TO ":APP_USER";

CREATE SCHEMA ":APP_SCHEMA";

GRANT USAGE ON SCHEMA ":APP_SCHEMA" TO ":APP_OWNER";

ALTER ROLE ":APP_OWNER" SET search_path TO ":APP_SCHEMA";
ALTER ROLE ":APP_USER" SET search_path TO ":APP_SCHEMA";

GRANT ALL PRIVILEGES ON SCHEMA ":APP_SCHEMA" TO ":APP_OWNER" WITH GRANT OPTION;
