-- Shadow
DROP SCHEMA IF EXISTS public;
DROP SCHEMA IF EXISTS ":APP_SCHEMA";

DROP ROLE IF EXISTS ":SHADOW_OWNER";
CREATE ROLE ":SHADOW_OWNER" WITH LOGIN PASSWORD '":SHADOW_OWNER_PASSWORD"';

GRANT CONNECT ON DATABASE ":POSTGRES_DB_SHADOW" TO ":SHADOW_OWNER";

CREATE SCHEMA ":APP_SCHEMA";

GRANT USAGE ON SCHEMA ":APP_SCHEMA" TO ":SHADOW_OWNER";

GRANT ALL PRIVILEGES ON SCHEMA ":APP_SCHEMA" TO ":SHADOW_OWNER" WITH GRANT OPTION;
