// Aurora DB statements
export const adminStatements: string[] = [
  /* SQL */ `DROP SCHEMA IF EXISTS ":APP_SCHEMA" CASCADE;`,

  /* SQL */ `AWS IAM REVOKE ":APP_USER" FROM '":APP_AWS_DB_CONNECT_ROLE_ARN"';`,
  /* SQL */ `AWS IAM REVOKE ":APP_OWNER" FROM '":APP_AWS_DB_CONNECT_ROLE_ARN"';`,

  /* SQL */ `DROP ROLE IF EXISTS ":APP_OWNER";`,
  /* SQL */ `CREATE ROLE ":APP_OWNER" WITH LOGIN;`,
  /* SQL */ `DROP ROLE IF EXISTS ":APP_USER";`,
  /* SQL */ `CREATE ROLE ":APP_USER" WITH LOGIN;`,

  // 👇 Allow admin to "be" app_owner for owner-sensitive DDL
  /* SQL */ `GRANT ":APP_OWNER" TO ":POSTGRES_USER";`,
  /* SQL */ `GRANT ":APP_USER" TO ":APP_OWNER";`,

  /* SQL */ `CREATE SCHEMA ":APP_SCHEMA" AUTHORIZATION ":APP_OWNER";`,

  /* SQL */ `AWS IAM GRANT ":APP_OWNER" TO '":APP_AWS_DB_CONNECT_ROLE_ARN"';`,
  /* SQL */ `AWS IAM GRANT ":APP_USER" TO '":APP_AWS_DB_CONNECT_ROLE_ARN"';`,

  /* SQL */ `ALTER ROLE ":APP_OWNER" SET search_path TO ":APP_SCHEMA";`,
  /* SQL */ `ALTER ROLE ":APP_USER" SET search_path TO ":APP_SCHEMA";`,
];

export const appUserStatements: string[] = [
  /* SQL */ `GRANT USAGE ON SCHEMA ":APP_SCHEMA" TO ":APP_USER";`,

  /* SQL */ `GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA ":APP_SCHEMA" TO ":APP_USER";`,
];

// DEV statements
export const devAdminStatements: string[] = [
  /* SQL */ `
    DO
    $$
    BEGIN
      IF EXISTS (SELECT FROM pg_catalog.pg_roles WHERE  rolname = '":APP_OWNER"') THEN
        REVOKE ALL PRIVILEGES ON DATABASE ":POSTGRES_DB" FROM ":APP_OWNER" CASCADE;
      END IF;
      IF EXISTS (SELECT FROM pg_catalog.pg_roles WHERE  rolname = '":APP_USER"') THEN
        REVOKE ALL PRIVILEGES ON DATABASE ":POSTGRES_DB" FROM ":APP_USER" CASCADE;
      END IF;
    END
    $$;
  `,

  /* SQL */ `DROP SCHEMA IF EXISTS public CASCADE;`,
  /* SQL */ `DROP SCHEMA IF EXISTS ":APP_SCHEMA" CASCADE;`,

  /* SQL */ `DROP ROLE IF EXISTS ":APP_OWNER";`,
  /* SQL */ `CREATE ROLE ":APP_OWNER" WITH LOGIN PASSWORD '":APP_OWNER_PASSWORD"';`,
  /* SQL */ `DROP ROLE IF EXISTS ":APP_USER";`,
  /* SQL */ `CREATE ROLE ":APP_USER" WITH LOGIN PASSWORD '":APP_USER_PASSWORD"';`,

  /* SQL */ `GRANT CONNECT ON DATABASE ":POSTGRES_DB" TO ":APP_OWNER";`,
  /* SQL */ `GRANT CONNECT ON DATABASE ":POSTGRES_DB" TO ":APP_USER";`,
  /* SQL */ `GRANT CREATE ON DATABASE ":POSTGRES_DB" TO ":APP_OWNER";`,
  /* SQL */ `GRANT CREATE ON DATABASE ":POSTGRES_DB" TO ":APP_USER";`,

  /* SQL */ `CREATE SCHEMA ":APP_SCHEMA" AUTHORIZATION ":APP_OWNER";`,

  /* SQL */ `ALTER ROLE ":APP_OWNER" SET search_path TO ":APP_SCHEMA";`,
  /* SQL */ `ALTER ROLE ":APP_USER" SET search_path TO ":APP_SCHEMA";`,
];

export const devAppUserStatements: string[] = [
  /* SQL */ `GRANT USAGE ON SCHEMA ":APP_SCHEMA" TO ":APP_USER";`,

  /* SQL */ `GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA ":APP_SCHEMA" TO ":APP_USER";`,
  /* SQL */ `ALTER DEFAULT PRIVILEGES IN SCHEMA ":APP_SCHEMA" GRANT SELECT, INSERT, UPDATE ON TABLES TO ":APP_USER";`,

  // NOTE: Sequences are not supported in Aurora DSQL
  // /* SQL */ `GRANT SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA ":APP_SCHEMA" TO ":APP_USER";`,
  // /* SQL */ `ALTER DEFAULT PRIVILEGES IN SCHEMA ":APP_SCHEMA" GRANT SELECT, UPDATE ON SEQUENCES TO ":APP_USER";`,
];

export const shadowStatements: string[] = [
  /* SQL */ `DROP SCHEMA IF EXISTS public;`,
  /* SQL */ `DROP SCHEMA IF EXISTS ":APP_SCHEMA";`,

  /* SQL */ `DROP ROLE IF EXISTS ":SHADOW_OWNER";`,
  /* SQL */ `CREATE ROLE ":SHADOW_OWNER" WITH LOGIN PASSWORD '":SHADOW_OWNER_PASSWORD"';`,

  /* SQL */ `GRANT CONNECT ON DATABASE ":POSTGRES_DB_SHADOW" TO ":SHADOW_OWNER";`,

  /* SQL */ `CREATE SCHEMA ":APP_SCHEMA";`,

  /* SQL */ `GRANT USAGE ON SCHEMA ":APP_SCHEMA" TO ":SHADOW_OWNER";`,
  /* SQL */ `GRANT ALL PRIVILEGES ON SCHEMA ":APP_SCHEMA" TO ":SHADOW_OWNER" WITH GRANT OPTION;`,

  /* SQL */ `ALTER ROLE ":SHADOW_OWNER" SET search_path TO ":APP_SCHEMA";`,
];
